POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###

GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM

###

GET http://localhost:3000/states/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM
###

POST http://localhost:3000/districts/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

GET http://localhost:3000/districts/17/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM
###

DELETE http://localhost:3000/districts/4/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM
###

PUT http://localhost:3000/districts/3/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM

{
  "districtName": "Nadia",
  "stateId": 5,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

GET http://localhost:3000/states/5/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjk3ODE0NjYzfQ.frvsgYfZQd67u3VwDWm5w9TNb_qsQV2WBVVQGjpv5CM
